// <auto-generated />
using MayetteRice.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MayetteRice.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240308141759_addImageUrlToProduct")]
    partial class addImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MayetteRice.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Flour"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Grains"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Cooking Oil"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Baking Goods"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MayetteRice.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscPrice")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A delicious rice that can fit to your family's needs!",
                            DiscPrice = 58.0,
                            ImageUrl = "",
                            Price = 59.0,
                            Title = "Angelica (1kg)"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "A delicious rice that can fit to your family's needs!",
                            DiscPrice = 53.0,
                            ImageUrl = "",
                            Price = 54.0,
                            Title = "Sinandomeng (1kg)"
                        });
                });

            modelBuilder.Entity("MayetteRice.Models.Product", b =>
                {
                    b.HasOne("MayetteRice.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
